<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>ClassicGrenades</RootNamespace>
    <AssemblyName>ClassicGrenades</AssemblyName>
    <Version>1.0.0</Version>
    <InformationalVersion>1.0.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>SteamTime</Authors>
    <Company>SteamTime</Company>
    <Product>ClassicGrenades</Product>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=.</PathMap>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <NoWarn>CS1591;CS0436;NU1701</NoWarn>
    <ScpslManagedDir Condition=" '$(ScpslManagedDir)' == '' ">$(HOME)/classic_dll_libs/</ScpslManagedDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="LabApi">
      <HintPath>$(ScpslManagedDir)LabApi-Publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ScpslManagedDir)Assembly-CSharp-Publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(ScpslManagedDir)Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>$(ScpslManagedDir)Mirror-Publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ScpslManagedDir)UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ScpslManagedDir)UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="YamlDotNet">
      <HintPath>$(ScpslManagedDir)YamlDotNet.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
